import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'], // 로마자(영문) 문자셋 지정
  display: 'swap',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body  className={inter.className}>{children}</body>
    </html>
  )
}